### ISSUE TITLE
About LICENSE, rewrite and other

### ISSUE THREAD

**Issue by lain-dono** [TheMightyFingers/mightyeditor#20]
Hi! I some time experimenting with the creation of editors for pixi. Something can be seen [here](https://github.com/oniproject/oniproject/tree/develop/redactor).

I would like to improve some of the mightyeditor and integrate their own experience. In particular:
* Fast and flexible ui with [vue.js](http://vuejs.org/)
* Edit PIXI.Spine
* Edit atlases
* Particles support
* Fast writing plug-ins and extensions (as part of the game data of the project)
* Scaffolding and testing
* Independence of the concrete server implementation

However, I would like to work on the project under a free license like GPL or MIT.

**Comment by stauzs** [comment]
*Fast and flexible ui with vue.js*
I can't see any benefit to change UI library - MightyEditor uses vaniilla.js + DOM - I doubt you can find anything faster than that. Probably something build on webgl :)

*Edit PIXI.Spine
Edit atlases
Particles support
Fast writing plug-ins and extensions (as part of the game data of the project)
Scaffolding and testing*
all these features seems more like a plugins - you can make your own plugins under GPL or any other license if you wish - you can use https://github.com/TheMightyFingers/mightyeditor/blob/master/client/MT/plugins/UserData.js
as example

*Independence of the concrete server implementation*
MightyEditor depends only on node.js and some node modules - check package.json

**Comment by cubemoon** [comment]
The MIT or BSD protocol may be more friendly to business and more conducive to promotion.
