### ISSUE TITLE
Firefox: "Open Game" button triggers security error

### ISSUE THREAD

**Issue by mildmojo** [TheMightyFingers/mightyeditor#23]
This project looks really interesting.

I jumped in just to see what the template looks like, but the "Open Game" button didn't work. In the console, I got the error: `Access to 'about::blank' from script denied` at MT.min.js:6:1418.

To reproduce:

1. From mightfingers.com, click "TRY IT NOW"
2. On the welcome screen (no sign-in), click "Create New Project"
3. Click "Create"
4. Click "Open Game"

Tested in Firefox 35.0.1 and Firefox Developer Edition 37.0a2 (2015-02-16), OSX 10.8.5.

**Comment by stauzs** [comment]
There are a lot of bugs in non chrome browsers.
Please use chrome / chromium instead. If you wish you can test and report all errors in firefox and I eventually will fix them :)

**Comment by mildmojo** [comment]
:+1:
