### ISSUE TITLE
Timeline - playing / previewing animation within ME is not accurate

### ISSUE THREAD

**Issue by ponderboy** [TheMightyFingers/mightyeditor#34]
Following scenario: 
I animated things within ME and it looks good. After export or open Game, the animation appears much faster. 

I assume that maybe hast to do with browser performance or something?! 
At the moment I adjust the fps to achieve more or less the speed I want, but of course that is not the most accurate way...

**Comment by stauzs** [comment]
I confirm - in ME preview - animation is a way slower as it should be - it's because of performance - but seems that frame skipping in ME is broken
