### ISSUE TITLE
After updating sprite atlas elements are wrong

### ISSUE THREAD

**Issue by ponderboy** [TheMightyFingers/mightyeditor#39]
The case: 
I want to add another graphic element to a spritesheet. I use the same elements as before plus a new one and create a spritesheet (using shoebox). Then update the spritesheet within ME as well as the atlas. Boom! All is messed up. 

I assume this only happens when you add new elements to a spritesheet?!

It's definitely annoying assinging all elements again manually.

**Comment by ponderboy** [comment]
Ahh, I found out why and a workaround. It applies the relevant frame of the sheet by number (or xml node that is) and not by name. 
For now I opened the atlas xml file in a code editor and cut out the new elements and pasted it at the end. 

´´´
<?xml version="1.0" encoding="UTF-8"?>
<TextureAtlas imagePath="ui.png">
	
	<SubTexture name="first-icon"	x="0"	y="619"	width="10"	height="10" frameX="-0" frameY="-0" frameWidth="10" frameHeight="10"/>
	<SubTexture name="second icon"	x="0"	y="630"	width="10"	height="10" frameX="-0" frameY="-0" frameWidth="10" frameHeight="10"/>
	<SubTexture name="third-icon"	x="0"	y="641"	width="10"	height="10" frameX="-0" frameY="-0" frameWidth="10" frameHeight="10"/>
</TextureAtlas>
````

**Comment by stauzs** [comment]
It's possible to store names instead of frame numbers. I just need to make sure that it won't break something else.
