### ISSUE TITLE
selecting transparent sprites doesn't work

### ISSUE THREAD

**Issue by ponderboy** [TheMightyFingers/mightyeditor#40]
I stumbled across this today. 
In the map editor you can't select transparent elements (transparent png for example). You can drag a rectangle selection around the element and it gets selected or you select its layer in in the object panel. However, once you want to select it with the mouse to drag it to another position, the element gets deselected. Same if you have a graphic with transparent parts. You can only select that when you click on a non transparent part.

**Comment by stauzs** [comment]
Yes - you are right.. 
I'll skip pixel perfect check if object is already selected
