### ISSUE TITLE
usability - "duplicate group" button in object panel

### ISSUE THREAD

**Issue by ponderboy** [TheMightyFingers/mightyeditor#41]
Many times you want to duplicate groups because you need the same structure and/or elements containing. Discussed also here:
http://www.html5gamedevs.com/topic/13359-reimport-or-reset-spritesheet/?p=79818

It'd be nice to have a function for that. So, for example an icon in the object panel and maybe a shortcut ( shift + ctrl + D ).

As you use fortawesome, I would suggest maybe this icon for now:
http://fortawesome.github.io/Font-Awesome/icon/files-o/

**Comment by stauzs** [comment]
isn't it same functionality as ctrl + C  -> ctrl + shift + V
if - yes - I'll add it right away before big update :)

please confirm

**Comment by ponderboy** [comment]
Yes, it's the same functionality.

My only personal issues I mentioned in the thread:
1. putting the duplicated on top of all groups not above the to be 
duplicated group
2. that sometimes it feels a bit slow and buggy)

Anyway, it'll help a lot and make working in the editor more intuitive.

Thanks again and keep it up Stausz!
