### ISSUE TITLE
Tile Layer: Cannot draw tiles

### ISSUE THREAD

**Issue by tomdevelops** [TheMightyFingers/mightyeditor#49]
Tile Layers cannot be selected. The console prints following error: "Failed to select an object".

**Comment by tomdevelops** [comment]
Could fix it with a complete phaser version, seems like the no physics one missing the tilemap part.
Now i can select the tilelayer, but cannot draw tile on them?

**Comment by stauzs** [comment]
Hi, I just synced github's master with mightyeditor.mightyfngers.com version - seems that some patches were applied only to online version

**Comment by stauzs** [comment]
This issue should be fixed now

**Comment by tomdevelops** [comment]
Thx, it's working now
