### ISSUE TITLE
Export > data only js  >>  not working

### ISSUE THREAD

**Issue by ponderboy** [TheMightyFingers/mightyeditor#56]
Well, like the title is saying. This export feature seems to not work. Same for data.json

**Comment by stauzs** [comment]
Most likely popup with data has been blocked.
![popup-blocked](https://cloud.githubusercontent.com/assets/4498213/13036200/640046a4-d369-11e5-9c6b-ab3bfbc6a7a1.png)

**Comment by ponderboy** [comment]
Ahh, we had this topic before. Sorry, I forgot. Thanks!
